// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgimdlziofsrizalbzwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnaW1kbHppb2Zzcml6YWxiendxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjM1MDIsImV4cCI6MjA1ODk5OTUwMn0.sbvwl4ecyLocoQ3MDr05c69gp_KfMsANjdUM6r3oWqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);